# Generated by Django 5.0.3 on 2024-03-09 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Giocatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Partita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(choices=[('I', 'In corso'), ('F', 'Finita')], default='I', max_length=1)),
                ('giocatore_attuale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partite_come_attuale', to='connect4.giocatore')),
                ('vincitore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partite_vinte', to='connect4.giocatore')),
            ],
        ),
        migrations.CreateModel(
            name='Mossa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colonna', models.IntegerField()),
                ('riga', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('giocatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect4.giocatore')),
                ('partita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mosse', to='connect4.partita')),
            ],
        ),
    ]
