# Generated by Django 5.0.3 on 2024-03-09 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect4', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partita',
            name='giocatore_attuale',
        ),
        migrations.AddField(
            model_name='partita',
            name='giocatore1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giocatore1', to='connect4.giocatore'),
        ),
        migrations.AddField(
            model_name='partita',
            name='giocatore2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giocatore2', to='connect4.giocatore'),
        ),
        migrations.AlterField(
            model_name='mossa',
            name='colonna',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)]),
        ),
        migrations.AlterField(
            model_name='mossa',
            name='riga',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
